### ISSUE TITLE
Cell becomes untouchable after animation in case if there is no more cell in a section

### ISSUE THREAD

**Issue by phalladar** [Ramotion/gliding-collection#6]
I'm noticing that when a row only contains one cell, `didSelectItemAt` is not firing when tapped. As long as more than one item is present everything works fine (including tapping the first cell). 

**Expected Behavior**
Even if a cell is the only cell in a particular row it should still call `didSelectItemAt` when tapped

**Actual Behavior**
When a cell is the only cell in a row `didSelectItemAt` does not trigger after the only cell is tapped.

**Comment by av0c0der** [comment]
@phalladar please make sure that you're assigned a `delegate` property and you're not going to check `willExpand` or `didExpand` methods, since they not going to fire because if you have only one row there is no way to actually `expand`. 

Note that in demo project `delegate` is not configured.

**Comment by phalladar** [comment]
Hey @Jauzee, the delegate is assigned which is why I'm receiving `didSelect` events for all rows with more than 1 cell. Are you not able to reproduce this? If not I can make a sample project for you.

**Comment by av0c0der** [comment]
@phalladar I'm unable to reproduce it, tried with only one cell & one row. Yes please.

**Comment by phalladar** [comment]
Here's the repo with my code: https://github.com/phalladar/gliding-bug

You'll notice that `didSelect` is not called for rows 3 and 4 where only one cell is present. 

Appreciate you taking a look.

**Comment by av0c0der** [comment]
@phalladar got it. This issue actually related to transition animation which have a bug inside of it (it remains overlay layer so we can't tap a cell more). I'll try to fix it asap.

**Comment by phalladar** [comment]
Awesome. 👍

**Comment by av0c0der** [comment]
Fixed in `1.0.3`

**Comment by stoneyanjun** [comment]
This bug still happen on 1.10 version.
I test the demo, also repro this bug by removing all image for the first item:
private func loadImages() {
    for item in items {
      let imageURLs = FileManager.default.fileUrls(for: "jpeg", fileName: item)
      var images: [UIImage?] = []
      for url in imageURLs {
        guard let data = try? Data(contentsOf: url) else { continue }
        let image = UIImage(data: data)
        images.append(image)
      }
      self.images.append(images)
    }
    
    self.images[0].removeAll()
  }
